version: "3.8"
services:
    odoo:
        build:
          context: .
        restart: unless-stopped
        volumes:
            - odoo-hmg-addons-5ad76303-812a-49e4-bf1d-66d349df4637:/mnt/extra-addons/
            - odoo-hmg-conf-8a0804b7-45d6-447e-8a9f-a62ee8a4fde7:/etc/odoo/
            - odoo-hmg-web-data-ae98af9f-eb4a-48b5-9cac-02dd40809583:/var/lib/odoo/
        ports:
            - "8069:8069"
        depends_on:
              - "db"

    db:
      image: postgres:15
      restart: unless-stopped
      container_name: postgresql
      environment:
        - POSTGRES_PASSWORD=odoo
        - POSTGRES_USER=odoo
        - POSTGRES_DB=odoo
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - "9432:5432"
      volumes:
        - ./odoo-db-data:/var/lib/postgresql/data/pgdata
      logging:
        driver: json-file
        options:
          max-size: "30m"
          max-file: "10"

volumes:
  odoo-db-data:
  
  odoo-hmg-addons-5ad76303-812a-49e4-bf1d-66d349df4637:
    external: true
  odoo-hmg-conf-8a0804b7-45d6-447e-8a9f-a62ee8a4fde7:
    external: true
  odoo-hmg-web-data-ae98af9f-eb4a-48b5-9cac-02dd40809583:
    external: true